#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

command_to_get_staged_files="git diff --name-only --staged | tee"
staged_files=$(eval "$command_to_get_staged_files")

if [[ $staged_files == *".php"* ]]; then
  clear && npm run php:lint && clear && echo "Verificando sintaxe do PHP 🔍" && sleep 1 && echo "Verificando sintaxe do PHP ✅"
fi

if [[ $staged_files == *".js"* ]]; then
  npm run lint && clear && echo "Verificando sintaxe do JS 🔍" && sleep 1 && echo "Verificando sintaxe do JS ✅"
  npm run build:js && clear && echo "Minificando JS 🔍" && sleep 1 && echo "Minificando JS (Se houver) ✅"
fi

if [[ $staged_files == *".css"* ]]; then
  npm run build:css && clear && echo "Minificando CSS 🔍" && sleep 1 && echo "Minificando CSS ✅"
fi

if [[ $staged_files == *".po"* ]]; then
  npm run pot && clear && echo "Atualizando arquivo .pot 🔍" && sleep 1 && echo "Atualizando arquivo .pot ✅"
fi
